Add a module settings for show icon image of the items  on inventory version 2
ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet pull request #8
Opened 2020-10-17 12:14 UTC by p4535992

OK , now i pretty confident, but i still don't like this part of the code:
```
      // Setting - Show icon on inventory list
      const settingsShowIconsOnInventoryList = game.settings.get(MODULE_ID, MySettings.showIconsOnInventoryList);
      sheetData?.inventory.forEach((itemType) => {
        itemType.items.forEach((item) => {
          if (!item.data.settings) {
            item.data.settings = {};
          }
          item.data.settings.showIconsOnInventoryList = settingsShowIconsOnInventoryList;
        });
      });
```
i don't like because i go to set the settings for each item, if you can suggest a workaround for using some global variable it will be perfect. 
Sincerely.

2020-10-17 15:10 UTC, akrigline commented
Since this is a user setting, we should be able to put a field on `sheetData` based on that user's setting.

Inside `CompactBeyond5eSheet.getData()`
```
try {
  if (game.settings.get(MODULE_ID, MySettings.showIconsOnInventoryList)) {
    sheetData.showInventoryIcons = true;
  }
} catch (e) {
  log(true, 'error trying to set showInventoryImages');
}

// return sheetData;
```

Inside `actor-inventory.hbs`
```
{{#if "../showInventoryImages" }}
  // image code
{{/if}}
```
`../` goes up one 'context' within the Handlebars data. You can see this same pattern used for `../isCharacter` inside the inventory file.

2020-10-18 07:39 UTC, p4535992 commented
Wow, didn't know that trick. Ty very much for the tip. Updated the  pull.

2020-10-19 15:27 UTC, akrigline requested changes

2020-10-19 15:27 UTC, akrigline commented on src/foundryvtt-5eOGLCharacterSheet.ts
> +import { DND5E } from '../../systems/dnd5e/module/config.js';
I don't think these are used anymore.

2020-10-19 15:28 UTC, akrigline commented
This looks great, thanks for the contribution!
I'll pull and test it tonight, merge after I test in 0.7.x.

2020-10-19 21:15 UTC, akrigline approved these changes
I'll pull this and do a quick test in 0.7.4 before merging, otherwise this looks done!

2020-10-20 02:55 UTC, merged